project:
  type: book
  output-dir: docs

book:
  title: "Sport Analytics Vignettes in R"
  author: "Sean Steele"
  date: last-modified
  date-format: "[Last Updated] MMMM, YYYY"
  chapters:
    - index.qmd
    - 01-data-collection.qmd
    - 02-data-management.qmd
    - 03-data-prep.qmd
    - 04-custom-functions.qmd
    - 05-data-viz.qmd
    - 06-statistical-analysis.qmd
    - 07-predictive-modeling.qmd
    - 08-ml-ai.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

